# Generated by Django 6.1.1 on 2026-09-08 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon identifier', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10)),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=30)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit / Debit Card'), ('cod', 'Cash on Delivery (COD)'), ('bank_transfer', 'Direct Bank Transfer / Wire')], default='credit_card', max_length=30)),
                ('shipping_method', models.CharField(default='Standard Atelier Courier', max_length=50)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Payment Pending'), ('confirmed', 'Order Confirmed & Assembling'), ('shipped', 'Dispatched / In Transit'), ('delivered', 'Delivered')], default='confirmed', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Needle & Thread Merchant Co.', max_length=150)),
                ('tagline', models.CharField(default='Fine Haberdashery, Artisan Threads & Precision Needles', max_length=255)),
                ('announcement_text', models.CharField(default='✨ Handcrafted Spring Release: Free worldwide shipping on orders over $50 | Use code NEEDLE15', max_length=255)),
                ('active_theme', models.CharField(choices=[('couture', '1. Atelier Couture (Haute Couture & Goldwork)'), ('sashiko', '2. Wabi-Sabi Sashiko (Japanese Mending & Indigo)'), ('quilter', '3. Modern Quilter Studio (Contemporary Craft & Sewing)'), ('leathercraft', '4. Heritage Leathercraft (Industrial Workshop & Rigging)'), ('botanical', '5. Botanical Dyehouse (Organic Plant-Dyed Silk & Linen)'), ('nordic', '6. Nordic Wool & Crewel (Scandinavian Minimalist Hygge)'), ('victorian', '7. Victorian Haberdashery (Antique Parlor & Filigree)'), ('neontuft', '8. Neon Tuft & Punch (Gen-Z Fiber Art & Modern Rug Punch)'), ('precision', '9. Precision Micro-Needle (High-Tech Industrial & Embroidery)'), ('boho', '10. Boho Tapestry & Weft (Artisan Weaving & Macramé)')], default='couture', max_length=30)),
                ('contact_email', models.EmailField(default='concierge@needletravel.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (800) 555-SEWN', max_length=50)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('instagram_handle', models.CharField(default='@needletravel_official', max_length=100)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.CharField(max_length=500)),
                ('badge', models.CharField(blank=True, help_text='e.g. Artisan Made, Best Seller, Limited', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.9'), max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=28)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Key-value pairs for technical specifications')),
                ('theme_niche', models.CharField(blank=True, help_text='Sample theme archetype this best represents', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('variant_name', models.CharField(blank=True, max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(default='standard', help_text='e.g. color, gauge, spool_weight', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('color_hex', models.CharField(blank=True, help_text='e.g. #D4AF37 for color swatches', max_length=20, null=True)),
                ('gauge_size', models.CharField(blank=True, help_text='e.g. Size 10 / 0.45mm', max_length=50, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('stock', models.PositiveIntegerField(default=35)),
                ('sku_suffix', models.CharField(blank=True, max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
        ),
    ]
