# Generated by Django 6.1.1 on 2026-09-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='active_theme',
            field=models.CharField(choices=[('couture', '1. Atelier Couture (Haute Couture & Goldwork)'), ('sashiko', '2. Wabi-Sabi Sashiko (Japanese Mending & Indigo)'), ('quilter', '3. Modern Quilter Studio (Contemporary Craft & Sewing)'), ('leathercraft', '4. Heritage Leathercraft (Industrial Workshop & Rigging)'), ('botanical', '5. Botanical Dyehouse (Organic Plant-Dyed Silk & Linen)'), ('nordic', '6. Nordic Wool & Crewel (Scandinavian Minimalist Hygge)'), ('victorian', '7. Victorian Haberdashery (Antique Parlor & Filigree)'), ('neontuft', '8. Neon Tuft & Punch (Gen-Z Fiber Art & Modern Rug Punch)'), ('precision', '9. Precision Micro-Needle (High-Tech Industrial & Embroidery)'), ('boho', '10. Boho Tapestry & Weft (Artisan Weaving & Macramé)'), ('baroque', '11. Baroque Ecclesiastical (Goldwork & Church Vestments)'), ('retro70s', '12. Retro 70s Earth Weaver (Vintage Jute, Hemp & Macramé)'), ('tactical', '13. Tactical Rigging (Mil-Spec Kevlar & Ballistic Awls)'), ('kawaii', '14. Kawaii Pastel Amigurumi (Ergonomic Hooks & Soft Fluff)'), ('gothic', '15. Dark Romantic Corsetry (Waxed Cord & Boning Needles)'), ('artnouveau', '16. Art Nouveau Lace (Whiplash Curves & Filigree Silks)')], default='couture', max_length=30),
        ),
    ]
